### ISSUE TITLE
usage of mark tab

### ISSUE THREAD

**Issue by lishenyu16** [HerbertHe/for-editor-herb#11]
I see your demo page has mark tag: 
==this is a mark tag==
could you tell me how do you convert above markdown syntax to html <mark>this is...</mark>. ?thanks!

**Comment by HerbertHe** [comment]
I have rewritten the syntax by `marked.js` renderer, you can follow the official document about renderer. About mark tag, I use RegExp written by myself, you can get it from `marked.ts`. About Html tag, I use `<mark></mark>` tag.
