### ISSUE TITLE
code <> crashes

### ISSUE THREAD

**Issue by lishenyu16** [HerbertHe/for-editor-herb#4]
after click code <>, it crashes and the error message is below:
![image](https://user-images.githubusercontent.com/16713047/79052276-1b5f1000-7bea-11ea-98ec-784ed2c1e26b.png)

**Comment by lishenyu16** [comment]
to be more exactly, 
after typing  ``` then press enter, app crashes, and shows above image error.

**Comment by lishenyu16** [comment]
the author of marked.js said that the issue should be here; [https://github.com/HerbertHe/for-editor-herb/blob/master/src/lib/helpers/marked.ts](url)

**Comment by HerbertHe** [comment]
Could you express this clearly? I do as what you said, but no error has been displayed...

**Comment by lishenyu16** [comment]
> Could you express this clearly? I do as what you said, but no error has been displayed...

I want to add a code block: 
```js
console.log('asdfasdf');
```

but after I typed 'js' then pressed 'Enter', app immediately crashed, showing the above image error.

**Comment by lishenyu16** [comment]
![image](https://user-images.githubusercontent.com/16713047/79084922-4f6e2a00-7ceb-11ea-9781-62f37829058a.png)

**Comment by lishenyu16** [comment]
as above image shows, after i typed:  ```js then press enter, app crashes

**Comment by HerbertHe** [comment]
Please following the `README.md` to update; after version 2.0.0,  the component allow you to highlight the language by yourself, [Use](https://github.com/HerbertHe/for-editor-herb#use)

**Comment by lishenyu16** [comment]
> Please following the `README.md` to update; after version 2.0.0, the component allow you to highlight the language by yourself, [Use](https://github.com/HerbertHe/for-editor-herb#use)

is the highlight.js a must for using the code block? I didn't use the highlight

**Comment by HerbertHe** [comment]
> > Please following the `README.md` to update; after version 2.0.0, the component allow you to highlight the language by yourself, [Use](https://github.com/HerbertHe/for-editor-herb#use)
> 
> is the highlight.js a must for using the code block? I didn't use the highlight

yes, it's required! I can't register all of the languages in the package, the `highlight.js` provide styles to render `code block` style.

**Comment by HerbertHe** [comment]
If everything is ok, please close the issue

**Comment by lishenyu16** [comment]
yes it's good now, thanks for your help!
