### ISSUE TITLE
Menu listings

### ISSUE THREAD

**Issue by ivanandonov** [HerbertHe/for-editor-herb#6]
https://github.com/HerbertHe/for-editor-herb/blob/9f6a6d8c28f2356fdccfa0a01fffe10c159c66b2/src/components/toolbar_left.tsx#L47

When we click on lets say BOLD on mobile and the menu doesn't hide after the click. Unfortunately our text is under the menu and we cant quite see what we just did unless we click someone else. We can just set all those "*Hidden" to true.
Also it would be great if we can make our own groups and have the control of which buttons will be in them.
The ability to add our own custom buttons will be also useful (H5 and H6 for example are missing).

**Comment by HerbertHe** [comment]
About `BOLD`, the next version will fix this trouble and you can control the buttons too, and H5 and H6 will be provided. About custom button, it is hard to provide. If you have more features wanted, please let me know
