### ISSUE TITLE
Can it be used in Vue?

### ISSUE THREAD

**Issue by lhlyu** [HerbertHe/for-editor-herb#8]
I can't react, but I think you write very well and want to use it in Vue

**Comment by HerbertHe** [comment]
Sorry, I haven't used Vue for a long time, and I have to prepare for my master degree entrance exam.

**Comment by lhlyu** [comment]
我发现react有很多好库，但是不能直接用于vue，难受~不学习react是因为它的可读性差，视图和逻辑竟然不分离

**Comment by HerbertHe** [comment]
哈哈哈，我恰恰相反，我喜欢纯的逻辑控制，react可扩展性很强而且没有太多的语法，改别人代码会容易很多的，但是一定要根据纯的逻辑来

**Comment by HerbertHe** [comment]
我就是因为想偷懒才找到的这个库，然后发现了好多问题，就重写了一部分内容并且扩展了marked的语法

**Comment by lhlyu** [comment]
我最近在用这个库 [Vditor](https://github.com/Vanessa219/vditor)，但是总感觉缺少一点灵魂，多了一些不必要的

**Comment by HerbertHe** [comment]
这个库太完整了，堆料堆得太厉害了。。。那个mermaid我好几个月都没解决bug，看看能不能找找灵感23333
