### ISSUE TITLE
Get the size of the editor not the window

### ISSUE THREAD

**Issue by ivanandonov** [HerbertHe/for-editor-herb#9]
https://github.com/HerbertHe/for-editor-herb/blob/539371f23d4e76654e9a08e72d8388cf63269028/example/src/app.tsx#L51

we can get this.$v.current.clientWidth and according to this value change the toolbars icons and groups. I have a case where i can have the editor in a column (50% width of the page) and then the icons go outside the toolbar.
![image](https://user-images.githubusercontent.com/1010243/79211806-6037b080-7e4f-11ea-8c3c-0626f5f70185.png)

**Comment by HerbertHe** [comment]
please update to the latest version, I have fixed this bug. If the bug still here, please it me know

**Comment by HerbertHe** [comment]
I also support localization, please follow `README` to use

**Comment by ivanandonov** [comment]
just updated to 2.3.5 and it seems the problem is still there
![image](https://user-images.githubusercontent.com/1010243/79215526-5bc1c680-7e54-11ea-8226-b1b864543ce3.png)

**Comment by ivanandonov** [comment]
> I also support localization, please follow `README` to use

i checked the README and its unclear how "const customLang: any" is used.
Probably "language: customLang"

**Comment by HerbertHe** [comment]
> > I also support localization, please follow `README` to use
> 
> i checked the README and its unclear how "const customLang: any" is used.
> Probably "language: customLang"

interface IWord as followed

**Comment by HerbertHe** [comment]
> just updated to 2.3.5 and it seems the problem is still there
> ![image](https://user-images.githubusercontent.com/1010243/79215526-5bc1c680-7e54-11ea-8226-b1b864543ce3.png)

In version 2.3.5, I have added `H5` and `H6`, and I have made title as an icon button like image.

**Comment by HerbertHe** [comment]
Here is the [Demo](https://goer.icu/for-editor-herb/)，it seems that everything is ok...

**Comment by ivanandonov** [comment]
> Here is the [Demo](https://goer.icu/for-editor-herb/)，it seems that everything is ok...

yes it works perfectly, i forgot to rerun the project after the update. thx
